{"name": "test_create_customer_and_verify_by_id", "status": "broken", "statusDetails": {"message": "NameError: name 'random' is not defined. Did you forget to import 'random'?", "trace": "@pytest.fixture\n    def test_customer_data():\n        return {\n>           \"firstname\": generate_random_string(),\n            \"lastname\": generate_random_string(),\n            \"email\": generate_random_email(),\n            \"telephone\": generate_random_phone(),\n            \"password\": \"hashed_pass\",  # Подставляй заранее хэш, если нужно\n            \"newsletter\": 0,\n            \"status\": 1,\n        }\n\ntests/test_customer.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nlength = 6\n\n    def generate_random_string(length=6):\n>       return ''.join(random.choices(string.ascii_letters, k=length))\nE       NameError: name 'random' is not defined. Did you forget to import 'random'?\n\ntests/test_customer.py:12: NameError"}, "start": 1746280502485, "stop": 1746280502485, "uuid": "4ffb0583-b18d-4b03-904e-2af231212417", "historyId": "097d1764a431dd8396e9eced2dc71f8c", "testCaseId": "097d1764a431dd8396e9eced2dc71f8c", "fullName": "tests.test_customer#test_create_customer_and_verify_by_id", "labels": [{"name": "story", "value": "Создание клиента"}, {"name": "feature", "value": "Клиенты"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "9957-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}