{"uuid": "8a1fb618-5c52-4b48-b57e-d2e59dd6b8e6", "children": ["26b79f59-9ade-44e9-8a42-cb1b02d76ea9", "4b43ff35-8139-49f1-9ef8-8047a98b7cd6", "6ce54f2e-dcf6-4530-8db0-50ecdc1df28e", "727f6491-954c-47cf-8b1c-c77c318b5c48", "349f367e-02f5-466f-8df4-1ccac9c5a17d"], "befores": [{"name": "connection", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n", "trace": "  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/aleks/QA-hw/opencart_db_framework/tests/conftest.py\", line 20, in connection\n    conn = pymysql.connect(\n        host=host,\n    ...<5 lines>...\n        autocommit=False  # для явного контроля транзакций\n    )\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 361, in __init__\n    self.connect()\n    ~~~~~~~~~~~~^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 668, in connect\n    self._get_server_information()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 1098, in _get_server_information\n    packet = self._read_packet()\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 744, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 798, in _read_bytes\n    raise err.OperationalError(\n        CR.CR_SERVER_LOST, \"Lost connection to MySQL server during query\"\n    )\n"}, "start": 1746280099019, "stop": 1746280099033}], "start": 1746280099019, "stop": 1746280100156}