{"name": "test_update_existing_customer", "status": "broken", "statusDetails": {"message": "pymysql.err.IntegrityError: (1062, \"Duplicate entry 'updated@example.com' for key 'email'\")", "trace": "connection = <pymysql.connections.Connection object at 0x102fa5d30>\ntest_customer_data = {'email': 'BegIQO@example.com', 'firstname': 'JjdzKP', 'lastname': 'PnsHvr', 'newsletter': 0, ...}\n\n    @allure.feature(\"Клиенты\")\n    @allure.story(\"Обновление клиента\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_update_existing_customer(connection, test_customer_data):\n        with allure.step(\"Создание клиента\"):\n            customer_id = create_customer(connection, test_customer_data)\n    \n        updated_data = {\n            \"firstname\": \"Updated\",\n            \"lastname\": \"Name\",\n            \"email\": \"updated@example.com\",\n            \"telephone\": \"9999999999\",\n        }\n    \n        with allure.step(\"Обновление данных клиента\"):\n            query = \"\"\"\n                UPDATE oc_customer\n                SET firstname = %s, lastname = %s, email = %s, telephone = %s\n                WHERE customer_id = %s\n            \"\"\"\n            with connection.cursor() as cursor:\n>               cursor.execute(query, (\n                    updated_data[\"firstname\"],\n                    updated_data[\"lastname\"],\n                    updated_data[\"email\"],\n                    updated_data[\"telephone\"],\n                    customer_id\n                ))\n\ntests/test_customer.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n.venv/lib/python3.13/site-packages/pymysql/cursors.py:153: in execute\n    result = self._query(query)\n.venv/lib/python3.13/site-packages/pymysql/cursors.py:322: in _query\n    conn.query(q)\n.venv/lib/python3.13/site-packages/pymysql/connections.py:563: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n.venv/lib/python3.13/site-packages/pymysql/connections.py:825: in _read_query_result\n    result.read()\n.venv/lib/python3.13/site-packages/pymysql/connections.py:1199: in read\n    first_packet = self.connection._read_packet()\n.venv/lib/python3.13/site-packages/pymysql/connections.py:775: in _read_packet\n    packet.raise_for_error()\n.venv/lib/python3.13/site-packages/pymysql/protocol.py:219: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xff&\\x04#23000Duplicate entry 'updated@example.com' for key 'email'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        # https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_err_packet.html\n        # Error packet has optional sqlstate that is 5 bytes and starts with '#'.\n        if data[3] == 0x23:  # '#'\n            # sqlstate = data[4:9].decode()\n            # TODO: Append (sqlstate) in the error message. This will be come in next minor release.\n            errval = data[9:].decode(\"utf-8\", \"replace\")\n        else:\n            errval = data[3:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.IntegrityError: (1062, \"Duplicate entry 'updated@example.com' for key 'email'\")\n\n.venv/lib/python3.13/site-packages/pymysql/err.py:150: IntegrityError"}, "steps": [{"name": "Создание клиента", "status": "passed", "start": 1746280560371, "stop": 1746280560383}, {"name": "Обновление данных клиента", "status": "broken", "statusDetails": {"message": "pymysql.err.IntegrityError: (1062, \"Duplicate entry 'updated@example.com' for key 'email'\")\n", "trace": "  File \"/Users/aleks/QA-hw/opencart_db_framework/tests/test_customer.py\", line 69, in test_update_existing_customer\n    cursor.execute(query, (\n    ~~~~~~~~~~~~~~^^^^^^^^^\n        updated_data[\"firstname\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        customer_id\n        ^^^^^^^^^^^\n    ))\n    ^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/cursors.py\", line 153, in execute\n    result = self._query(query)\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/cursors.py\", line 322, in _query\n    conn.query(q)\n    ~~~~~~~~~~^^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 563, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 825, in _read_query_result\n    result.read()\n    ~~~~~~~~~~~^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 1199, in read\n    first_packet = self.connection._read_packet()\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/connections.py\", line 775, in _read_packet\n    packet.raise_for_error()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/protocol.py\", line 219, in raise_for_error\n    err.raise_mysql_exception(self._data)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^\n  File \"/Users/aleks/QA-hw/opencart_db_framework/.venv/lib/python3.13/site-packages/pymysql/err.py\", line 150, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"}, "start": 1746280560383, "stop": 1746280560386}], "start": 1746280560371, "stop": 1746280560396, "uuid": "6add5064-fe4f-4113-80a9-4e82886e4087", "historyId": "b2b1532b61fe997b7ba97520860addcb", "testCaseId": "b2b1532b61fe997b7ba97520860addcb", "fullName": "tests.test_customer#test_update_existing_customer", "labels": [{"name": "feature", "value": "Клиенты"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Обновление клиента"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_customer"}, {"name": "host", "value": "MacBook-Air-2.local"}, {"name": "thread", "value": "10763-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_customer"}]}